server {
    listen 8080;
    server_name localhost;

    client_max_body_size 1000000;

    error_page 404 /404.html;

    # RULE 1: "/" GET ONLY
    location / {
        root ./www;
        index index.html;
        methods GET;
    }

    # RULE 2: .bla → CGI test executable
    location / {
        root ./YoupiBanane;
        methods POST;
        cgi .bla ./cgi_test;
    }

    # RULE 3: /post_body POST only, maxBody 100
    location /post_body {
        root ./www;
        methods POST;
        client_max_body_size 100;
    }

    # RULE 4: /directory/
    location /directory {
        root ./YoupiBanane;
        methods GET;
        index youpi.bad_extension;
        autoindex on;
    }
}
